insert into public.achievements (id, title, description, icon, tier, category, sort_order) values
  ('first_bet', 'Перший крок', 'Зробити першу ставку', '🎯', 'bronze', 'onboarding', 1),
  ('first_win', 'Перша перемога', 'Виграти першу ставку', '🏆', 'bronze', 'onboarding', 2),
  ('profile_complete', 'Свій чоловік', 'Унікальний нік та аватар', '👤', 'bronze', 'onboarding', 3),
  ('donor_first', 'Підтримав ЗСУ', 'Перший підтверджений донат', '💛', 'bronze', 'onboarding', 4),
  ('total_bets_10', 'Активний', 'Зробити 10 ставок', '📊', 'silver', 'volume', 5),
  ('total_bets_50', 'Постійний', 'Зробити 50 ставок', '📈', 'silver', 'volume', 6),
  ('total_bets_100', 'Легенда', 'Зробити 100 ставок', '⭐', 'gold', 'volume', 7),
  ('loyal_full_season', 'Вірний фанат', 'Ставки на всі випуски сезону', '🎬', 'gold', 'volume', 8),
  ('streak_3', 'Запал', '3 виграшні ставки поспіль', '🔥', 'silver', 'streaks', 9),
  ('streak_5', 'На хвилі', '5 виграшних ставок поспіль', '🔥', 'gold', 'streaks', 10),
  ('streak_10', 'Непереможний', '10 виграшних ставок поспіль', '⚡', 'platinum', 'streaks', 11),
  ('underdog_winner', 'Темна конячка', 'Виграш з коефіцієнтом від 5.0', '🐎', 'gold', 'skill', 12),
  ('high_roller_1000', 'Ва-банк', 'Ставка від 1000 балів і виграш', '💰', 'gold', 'skill', 13),
  ('perfect_episode', 'Ясновидець', 'Усі ваші ставки у випуску виграшні', '🔮', 'platinum', 'skill', 14),
  ('lightning_first', 'Блискавка', 'Перша ставка на lightning-подію', '⚡', 'bronze', 'lightning', 15),
  ('lightning_won', 'Швидкі гроші', 'Виграшна lightning-ставка', '💸', 'silver', 'lightning', 16),
  ('lightning_hunter', 'Мисливець', '10 ставок на lightning-події', '🎯', 'gold', 'lightning', 17),
  ('season_winner_predicted', 'Пророк', 'Вгадано переможницю сезону', '👑', 'platinum', 'season', 18),
  ('season_top3', 'П''єдестал', 'Топ-3 сезонного лідерборду', '🥉', 'gold', 'season', 19),
  ('season_top1', 'Чемпіон', '1 місце сезонного лідерборду', '🥇', 'platinum', 'season', 20),
  ('donor_1000', 'Меценат', 'Сумарно 1000+ одиниць підтверджених донатів', '💎', 'gold', 'donor', 21),
  ('donor_5000', 'Філантроп', 'Сумарно 5000+ одиниць підтверджених донатів', '✨', 'platinum', 'donor', 22)
on conflict (id) do nothing;
